server:
  port: 7000

spring:
  application:
    name: admin

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务的地址 不要加http

oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4GCDgGAt3xHLoMmDZvDi
  accessKeySecret: 0fiIewaAVQdFVT3RuGgHn9h1jKpCKd
  bucketName: campus-deal